# Install unzip
- name: Install unzip for unarchive module
  yum: name=unzip state=present

# Install consul if not installed
- name: Check if consul is installed
  stat: path=/usr/local/bin/consul
  register: consul_bin
- block:
  - name: Download and unzip Consul {{ consul_version }} command
    unarchive: src="https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip" dest=/tmp copy=no

  - name: Add execution permission to consul command
    file: path=/tmp/consul state=file mode="0755"

  - name: Move consul command
    command: mv /tmp/consul /usr/local/bin/consul

  when: not consul_bin.stat.exists

- name: Create consul setting directory
  file: path=/etc/consul.d state=directory owner=root group=root mode=0755
- name: Create common consul script for CentOS 6
  template: src="consul" dest="/etc/init.d/consul" owner=root group=root mode=0755
# Start consul and create autostart setting
- name: Autostart Consul
  service: name=consul state=started enabled=yes
# Install dnsmasq
- name: Install dnsmasq
  yum: name=dnsmasq state=present
- name: Create dnsmasq setting
  template: src="dnsmasq.conf" dest="/etc/dnsmasq.conf" owner=root group=root mode=0644
- name: Start dnsmasq and create autostart setting
  service: name=dnsmasq state=restarted enabled=yes
- name: Replace /etc/resolv.conf that includes localhost as nameserver
  template: src="resolv.conf" dest="/etc/resolv.conf" owner=root group=root mode=0644
- name: Forbid NetworkManager from overwriting /etc/resolv.conf
  lineinfile: dest=/etc/NetworkManager/NetworkManager.conf line="dns=none"
# Create setting for Consul server or Consul client
- name: Create sysconfig file for environments
  template: src="consul.j2" dest="/etc/sysconfig/consul" owner=root group=root mode=0644
