# Create Consul client settings
- name: Create sysconfig file for environments
  template: src="consul/consul" dest="/etc/sysconfig/consul" owner=root group=root mode=0644
# Cloudera-specific setting
- name: Create impala service information for consul
  template: src="consul/impala.json" dest="/etc/consul.d/impala.json" owner=root group=root mode=0644
# Common task
- name: Restart consul
  service: name=consul state=restarted
# Install dnsmasq
- name: Install dnsmasq
  yum: name=dnsmasq state=present
- name: Create dnsmasq setting
  template: src="dnsmasq/dnsmasq.conf" dest="/etc/dnsmasq.conf" owner=root group=root mode=0644
- name: Start dnsmasq and create autostart setting
  service: name=dnsmasq state=restarted enabled=yes
- name: Replace /etc/resolv.conf that includes localhost as nameserver
  template: src="dnsmasq/resolv.conf" dest="/etc/resolv.conf" owner=root group=root mode=0644
- name: Forbid NetworkManager from overwriting /etc/resolv.conf
  lineinfile: dest=/etc/NetworkManager/NetworkManager.conf line="dns=none"
