- name: Sample Manager
  hosts: all
  sudo: yes
  vars:
    php_version: 5.6.15
  tasks:
    # Disable SELinux for FuelPHP application
    - name: Disable SELinux
      selinux: state=disabled
    # Change timezone
    - name: Change timezone from UTC to JST
      command: cp -p /usr/share/zoneinfo/Japan /etc/localtime
    # Add repository for installing Nginx and PHP
    - name: Add repository 'remi-repo'
      yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present
    # Nginx
    - name: Install nginx
      yum: name=nginx state=present
    - name: Start nginx
      service: name=nginx state=started
    - name: Set nginx autostart
      command: chkconfig nginx on
    - name: Configure nginx
      template: src="templates/nginx/hashicorp-sample-manager.conf" dest="/etc/nginx/conf.d/hashicorp-sample-manager.conf" owner=root group=root
    # Git
    - name: Install git
      yum: name="git" state=present
    # PHP and php-fpm
    - name: Install PHP libraries and php-fpm
      yum: name={{ item }} enablerepo=remi-php56 state=present
      with_items:
        - php-{{ php_version }}
        - php-devel-{{ php_version }}
        - php-fpm-{{ php_version }}
        - php-cli-{{ php_version }}
        - php-mbstring-{{ php_version }}
        - php-mysqlnd-{{ php_version }}
        - php-process-{{ php_version }}
        - php-xml-{{ php_version }}
        - php-opcache-{{ php_version }}
        - php-bcmath-{{ php_version }}
    - name: Start php-fpm
      service: name=php-fpm state=started
    - name: Set php-fpm autostart
      command: chkconfig php-fpm on
    - name: Configure php-fpm
      template: src="templates/php-fpm/www.conf" dest="/etc/php-fpm.d/www.conf" owner=root group=root
      notify:
        - Restart php-fpm
    # Change permission for installing sample FuelPHP application
    - name: Allow permission to /home/vagrant
      file: path=/home/vagrant state=directory mode=0755
    # Sample FuelPHP application
    - name: Clone sample FuelPHP application
      git: repo=https://github.com/muziyoshiz/hashicorp-sample-manager.git
           dest=/home/vagrant/hashicorp-sample-manager
           version=master
           accept_hostkey=yes
           force=yes
      sudo: no
    # Execute Composer
    - name: Update Composer itself
      command: php composer.phar self-update
      sudo: no
      args:
        chdir: /home/vagrant/hashicorp-sample-manager
    - name: Set GitHub Token
      command: php composer.phar config --global github-oauth.github.com 76d3b71859c3f511a8f7cc471667b5f4516a6387
      sudo: no
      args:
        chdir: /home/vagrant/hashicorp-sample-manager
    - name: Update libraries
      command: php composer.phar update
      sudo: no
      args:
        chdir: /home/vagrant/hashicorp-sample-manager
    # Configure settings for FuelPHP
    - name: Allow permission to /home/vagrant/hashicorp-sample-manager/fuel/app/logs
      file: path=/home/vagrant/hashicorp-sample-manager/fuel/app/logs state=directory mode=0777
    - name: Set timezone to /etc/php.ini for FuelPHP logging
      replace: dest=/etc/php.ini regexp='^;date\.timezone =$' replace='date.timezone = "Asia/Tokyo"' backup=yes
      notify:
        - Restart php-fpm
    # Install MariaDB client for testing
    - name: Install MariaDB Client
      yum: name=mariadb state=present
    # Restart nginx always at last
    - service: name=nginx state=restarted
  handlers:
    - name: Restart php-fpm
      action: service name=php-fpm state=restarted
