# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "quickstart/cdh"

  # Hostname for Consul
  # NOTICE: Following setting does not have any effect to hostname command.
  #         Default hostname is "quickstart.cloudera" and I can not change it.
  #         This is CentOS6-specific issue or this-box-file-specific issue?
#  config.vm.hostname = "cdh-quickstart"

  config.vm.network "private_network", ip: "192.168.33.20"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/cdh_quickstart.yml"
  end
end
