- name: Sample MariaDB Server
  hosts: all
  sudo: yes
  tasks:
    # Change timezone
    - name: Change timezone from UTC to JST
      command: cp -p /usr/share/zoneinfo/Japan /etc/localtime
    # Add repository for yum
    - name: Add repository 'remi-repo'
      yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present
    # Install MariaDB
    - name: Install MariaDB
      yum: name="{{ item }}" state=present
      with_items:
        - mariadb
        - mariadb-server
        - MySQL-python # required by mysql_db and mysql_user module
    - name: Start MariaDB and create autostart setting
      service: name=mariadb state=started enabled=yes
    # Set root account
    - name: Set root account of MariaDB
      mysql_user:
        name: root
        password: "dummy password"
        host: localhost
    # Create .my.cnf for creating database
    - name: Create /root/.my.cnf
      template: src=templates/mariadb/my.cnf dest="/root/.my.cnf" mode=0600
    # Create database "sample"
    - name: Create database "sample"
      mysql_db: name=sample state=present
    # Create "manager" account of MariaDB and grant all plivileges of sample database
    - name: Create "manager" account of MariaDB
      mysql_user:
        name: manager
        password: "dummy mgr password"
        priv: "sample.*:ALL"
        host: 192.168.33.10
        state: present
