# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Common settings
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "512"
    vb.cpus = 1
  end

  # Consul Server
  config.vm.define "consul1" do |c|
    c.vm.hostname = "consul1"
    c.vm.network "private_network", ip: "192.168.33.12"

    c.vm.provision "ansible" do |ansible|
      ansible.playbook = "../consul/playbook-consul.yml"
    end
  end

  # MariaDB Server
  config.vm.define "mariadb1" do |c|
    c.vm.hostname = "mariadb1"
    c.vm.network "private_network", ip: "192.168.33.11"

    c.vm.provision "ansible" do |ansible|
      ansible.playbook = "../mariadb/playbook-mariadb.yml"
    end
  end

  # Sample Manager Server
  config.vm.define "manager1" do |c|
    c.vm.hostname = "manager1"
    c.vm.network "private_network", ip: "192.168.33.10"

    c.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    c.vm.provision "ansible" do |ansible|
      ansible.playbook = "../manager/playbook-manager.yml"
    end
  end

  # Cloudera QuickStart VM
  config.vm.define "cdh-quickstart" do |c|
    c.vm.box = "quickstart/cdh"

    c.vm.hostname = "quickstart.cloudera"
    c.vm.network "private_network", ip: "192.168.33.20"

    c.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "8192"
    end

    c.vm.provision "ansible" do |ansible|
      ansible.playbook = "../cdh-quickstart/playbook-cdh-quickstart.yml"
    end
  end
end
